# -*- coding: utf-8 -*-
"""Digit Recognition 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cgl0qs-0TlwtVlU4Yj0GJSNWSYMMWIop
"""

import cv2
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
X,y=fetch_openml("mnist_784",version=1,return_X_y=True)
print(pd.Series(y).value_counts())
classes=["0","1","2","3","4","5","6","7","8","9"]
nclasses=len(classes)

samples=5
figure=plt.figure(nclasses*2,(1+samples*2))
indexClass=0
for i in (classes):
  index=np.flatnonzero(y==i)
  index=np.random.choice(index,samples,replace=False)
  data=0
  for f in (index):
    data2=data*nclasses+indexClass+1
    graph=plt.subplot(samples,nclasses,data2)
    graph=sns.heatmap(np.array(X.loc[f]).reshape(28,28),cmap=plt.cm.gray,xticklabels=False,yticklabels=False,cbar=False)